### ISSUE TITLE
cant get user from user id 

### ISSUE THREAD

**Issue by Eitan222** [TimMcCool/scratchattach#173]
basically i'm trying to get the host of a studio but the only studio host related function in scratchattach is "studio.host_id" which does not output the username.... and you cant get a user offline with id only... 

```
studio = scratchattach.get_studio(id[1])
username = scratchattach.????(studio.host_id) < how do i make this work
user = scratchattach.get_user(username) 
```

**Comment by TimMcCool** [comment]
It's not possible to get anything offline at all, you need an internet connection to request data from the Scratch API.

It's also not possible to get studios or users based on ID because Scratch API doesn't provide an API for that. **You can get the studio host by getting the first / top manager:**

```py
studio = scratchattach.get_studio(id[1])
user = studio.managers()[0] # This will get the studio host as User object
```
