### ISSUE TITLE
after backpacking cloud requests sprite and moving it to another project, it is unable to connect to scratchattach

### ISSUE THREAD

**Issue by blorpstorp** [TimMcCool/scratchattach#179]
ive tried multiple times and the only way i can get it to work is if i make a new project and then import the cloud requests template into scratch and then move all my sprites into that project.

**Comment by TheCommCraft** [comment]
Maybe the cloud variables were converted to normal variables (convert them back to cloud variables) or the @timeout variable is zero (put it to 10)

**Comment by TimMcCool** [comment]
Backpacking the sprite will break the cloud variables. Instead of backpacking the cloud requests sprite, backpack all other sprites and move them to the cloud requests project (there are other possible solutions too, you could create all necessary cloud variables before importing the CR sprite from a sprite3 file, then it would work too)
