### ISSUE TITLE
Response error

### ISSUE THREAD

**Issue by JustablockCode** [TimMcCool/scratchattach#187]
So if user makes cloud request and scrolls or switches tab then data corrupts(even with no packet loss).

**Comment by JustablockCode** [comment]
i think its smth with scratch code

**Comment by Ryan-shamu-YT** [comment]
> i think its smth with scratch code

I have also seen this issue in other projects which load PFP and other info which is large

**Comment by redspacecat** [comment]
> So if user makes cloud request and scrolls or switches tab then data corrupts(even with no packet loss).

I have experienced this too with making a comment loader

**Comment by TimMcCool** [comment]
This happens because scratch runs projects at a lower FPS rate when the tab isn't opened, therefore some of the data isn't received by the project. Can't be fixed unfortunately - tell the users of your project to not switch tabs during the loading process.

btw, I wouldn't recommend you to send the pixel data using hex color values. convert the hex values to 8-digit-long base10 integers and send these integers instead (scratch can render this kind of color value too). scratchattach will encode values that contain both numbers and letters (therefore a 6 digit hex code is 12 digits long in the encoded value), but it won't encode values that only contain numbers (therefore an 8 digit base10 integer is only 8 digits long in the encoded vlaue)

**Comment by Waakul** [comment]
> I am working with the OP on a project and this is the result of the bug:
> 
> ![image](https://private-user-images.githubusercontent.com/83490776/318911161-2ea039d7-8fef-40d2-8155-139b7f9431d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4OTQ2MTQsIm5iZiI6MTcxODg5NDMxNCwicGF0aCI6Ii84MzQ5MDc3Ni8zMTg5MTExNjEtMmVhMDM5ZDctOGZlZi00MGQyLTgxNTUtMTM5YjdmOTQzMWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDE0MzgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2MjMzOWQzYzg5OGExM2YzMzc5NzRmYTdjZTMwMjA3YWYzZWM1MTk1NzE3NTVjOTRhYjIyNjYxOWQzNmUyYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1iB38jQPzpcibbzOjZ4Q5jdzF4-27AKJROINgYZJWSo)
> 
> Please fix this, projects which send more than 3000 characters seem to mostly suffer from this, e.g. PFP renderers and others.

You can fix this with a simple method of decoding it into a string and cutting it into parts. see my pfp render project where i managed to get alot of resolution without data loss: https://[scratch.mit.edu/projects/987765422/](https://scratch.mit.edu/projects/987765422/)
