### ISSUE TITLE
[enhancement] Add the option to save cloud variable updates in a cloud connection

### ISSUE THREAD

**Issue by TheCommCraft** [TimMcCool/scratchattach#198]
When you connect to a cloud variable server, a new websocket gets created. It only gets used to set variables. Maybe you could add an option where it is used in a thread to receive cloud variable updates and also save them so you can access the current variable values at any time without more manual work. This would have the added bonus that getting cloud variable values would use less cpu on the cloud host server.

**Comment by TimMcCool** [comment]
will be added

**Comment by TimMcCool** [comment]
basically this can already be done using cloud events. I would have to figure out how to use a Websocket object that is currently running .recv() to send data. (I will probably have to implement an exception handler because sending data on an object currently running .recv() will cause .recv() to return an error)

**Comment by TheCommCraft** [comment]
Even with multithreading enabled?

**Comment by TheCommCraft** [comment]
So will it be added or not?

**Comment by TimMcCool** [comment]
It will be added. At the moment, scratchattach is opening 3 connections when starting a cloud requests instance. The first connection is just plain unnecessary / isn't used anyways, but is still opened due to the code being quite unoptimised. The second connection is for listening for cloud updates, the third connection is for sending data. I'll reduce the amount of connections to 1 and add a conn.get_var function

**Comment by TheCommCraft** [comment]
Great!!
