### ISSUE TITLE
Issue getting messages

### ISSUE THREAD

**Issue by CreeperKing77** [TimMcCool/scratchattach#203]
I can get messages normally using session.messages(limit=#, offset=#), up to a certain amount, but once i request a decent number at once (say, 30) it gives me {'code': 'BadRequest', 'message': ''}

it appears I can get exactly 40 messages at a time, I do not know if this is intentional or not but can't find anywhere that it says if it is.

Edit: temporarily solved by importing messages in batches, but this slows down the program significantly

**Comment by TimMcCool** [comment]
the Scratch API doesn't allow getting more than 40 messages at once. (The same limit applies to getting studies, projects. followers etc.).


I can get messages normally using session.messages(limit=#, offset=#), up to a certain amount, but once i request a decent number at once (say, 30) it gives me {'code': 'BadRequest', 'message': ''}

it appears I can get exactly 40 messages at a time, I do not know if this is intentional or not but can't find anywhere that it says if it is.

`Edit: temporarily solved by importing messages in batches, but this slows down the program significantly
`
That's the only way to get more than 40 messages
