### ISSUE TITLE
Bug in the function of obtaining cloud variables

### ISSUE THREAD

**Issue by Cosmanderio** [TimMcCool/scratchattach#218]
Hello,
I noticed that the functions to get cloud variables from scratchattach only seem to work for variables whose value has been changed recently in the history of cloud variables.
Is this normal and is there a way to get older variables?
Goodbye

**Comment by TheCommCraft** [comment]
Normally you can receive the cloud variable data from the websocket but
this sadly isn't working anymore because scratch removed it for some reason
which is also the reason why scratch cloud variabled don't seem to be
persistent anymore

Cosmanderio ***@***.***> schrieb am Do., 27. Juni 2024, 17:33:
