### ISSUE TITLE
I need [ , ] , { and } characters

### ISSUE THREAD

**Issue by Spike1377** [TimMcCool/scratchattach#225]
I really need [ ,],{ and } characters, i tryed editing the encoder python script and CloudRequests_Template.sb3 to add these in but it didnt work.

Can you also add that special é character, as im trying to make wikipedia in scratch and [Chloé Hayden's](https://en.wikipedia.org/wiki/Chloé_Hayden) page dosent work.
can you just add all the askii characters? thanks.

for the mean time ill translate the characters i need to other characters with .replace or ill just write my own encoder.

for all the ones im using: https://rexscratch.github.io/sfeplus-injector/ then press expanded++

**Comment by MinePossu** [comment]
I don't know if intended but you can replace the encoder letters. 
example:
scratch3.encoder.letters = ["a", "A", "b", "B", "c", "C", "d", "D", "e", "E", "f", "F", "g", "G", "h", "H", "i", "I", "j", "J", "k", "K", "l", "L", "m", "M", "n", "N", "o", "O", "p", "P", "q", "Q", "r", "R", "s", "S", "t", "T", "u", "U", "v", "V", "w", "W", "x", "X", "y", "Y", "z", "Z", "~", " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "=", "+", "-", "_", "", "", "|", "\\", ";", ",", "\"", "'", ",", ".", "?", "/", "<", ">", "`"]

**Comment by namtacs** [comment]
you can edit the letters by using .replace_char(oldc,newc) or replace them completely like above (just make sure the list isn't longer than 100 and is padded at the start with 10 None's). And replace them accordingly in the sb3.

Also, the above list won't work because of special characters. Replace """ with "\"" and "\" with "\\".

The OP's perfect list would be [None,None,None,None,None,None,None,None,None,None,"1","2","3","4","5","6","7","8","9","0"," ","a","A","b","B","c","C","d","D","e","E","f","F","g","G","h","H","i","I","j","J","k","K","l","L","m","M","n","N","o","O","p","P","q","Q","r","R","s","S","t","T","u","U","v","V","w","W","x","X","y","Y","z","Z","*","/",".",",","!",'"',"§","$","%","_","-","(","´",")","`","?","@","#","~",";",":","+","&","|","^","'","é"]
See, it's not longer than 100 because i removed the "new line" entry that isn't actually used and added the é instead to the end. You will have to update the sprite accordingly.

**Comment by TheCommCraft** [comment]
It is actually used for lists in cloud requests i think

namtacs ***@***.***> schrieb am Mi., 31. Juli 2024, 07:43:

**Comment by namtacs** [comment]
> It is actually used for lists in cloud requests i think

Yes, and because of that, you need to keep the **";"** symbol at index 89.

**Comment by kakeruzoku** [comment]
```python
import scratchattach as scratch3
scratch3.Encoding.replace_char(old_char, new_char)
```
You can change the text with . This is a built-in function, so it will work.

**Comment by namtacs** [comment]
I already mentioned that and the proper list https://github.com/TimMcCool/scratchattach/issues/225?notification_referrer_id=NT_kwDOBbeO9bQxMTcwMDE2NDMwOTo5NTkxNTc2NQ#issuecomment-2259715551

**Comment by kakeruzoku** [comment]
sorry

**Comment by Spike1377** [comment]
Guys sorry I never responded, I ended up making my own encoder that fixed this problem but now I've lost interest in what I was programming.
