### ISSUE TITLE
session.connect_cloud() doesn't work

### ISSUE THREAD

**Issue by mehonje** [TimMcCool/scratchattach#281]
Here's my code-
import scratchattach as sa

session = sa.login('x', 'x')
cloud = session.connect_cloud('1049536501')

That gives this error-
Traceback (most recent call last):
  File "c:\Users\x\Desktop\py_work\scratchattachServer", line 6, in <module>
    cloud = session.connect_cloud('1049536501')

TypeError: Session.connect_cloud() takes 1 positional argument but 2 were given
In the example, there's only one argument, the project id. Why does it not like the new id? Where is the second one?

I'm using 0.4.2

**Comment by kakeruzoku** [comment]
In 0.4.2 you need to specify the ID with `project_id` .
```py
session = sa.login('x', 'x')
cloud = session.connect_cloud(project_id='1049536501')
cloud.set_var("variable", "value")
```
Click [here](https://pypi.org/project/scratchattach/0.4.2/ ) for more details.
**We recommend updating Scratchattach.**
`pip install -U scratchattach`

**Comment by FAReTek1** [comment]
there are two arguments because this is a method of an object. The first parameter is self (passed automatically), and the second is the project id you passed in. however, in 0.4.2, the method only wants one positional argument (self), and a keyword argument (`project_id`), whose name must be explicitly passed as an argument, i.e. ```py
session.connect_cloud(```**`project_id=`**```1234)
```

**Comment by TimMcCool** [comment]
update to the latest scratchattach version (v2.1.6). 0.4.2 is very outdated
