### ISSUE TITLE
CloudRequests.get_timestamp() not returning the actual timestamp

### ISSUE THREAD

**Issue by TheCommCraft** [TimMcCool/scratchattach#92]
CloudRequests with load_from_websocket=True don't return the right timestamp when using CloudRequests.get_timestamp() because WsCloudEvents doesn't return the right timestamp

**Comment by TimMcCool** [comment]
Will be fixed

**Comment by TimMcCool** [comment]
CloudRequests.get_timestamp() returns the time in milliseconds since the epoch, which is also the timestamp that Scratch's clouddata logs uses (as far as I know)

**Comment by TheCommCraft** [comment]
But the timestamp used is the one when the event is triggered

Tim ***@***.***> schrieb am So., 11. Juni 2023, 16:38:

**Comment by TimMcCool** [comment]
The websocket doesn't provide the timestamp of when the cloud variable was set (unlike the clouddata log). The timestamp of when the event is triggered should be about the same as the timestamp of when the cloud variable was set because transmitting the websocket message only takes a few milliseconds. Getting the exact timestamp would require checking the clouddata log.

**Comment by TheCommCraft** [comment]
Yeah, but the same thing is done when using CloudRequests.get_requester()

Tim ***@***.***> schrieb am Mo., 12. Juni 2023, 10:28:

**Comment by TimMcCool** [comment]
There is no way to get the requester without looking in the clouddata log. But you can get almost the exact timestamp by using the timestamp of when the event was triggered. I am not planning to change it

**Comment by TimMcCool** [comment]
client.get_exact_timestamp() will be added in v1.2.6, it will return the exact timestamp of the request
